### PR TITLE
Fix issues with rerunning tests after a sync

### LINKED ISSUE #6229: Analyzer spins forever, sometimes
According to the UI there is a single message (probably: yay exemplary), but the message doesn't show up.

image

### LINKED ISSUE #6236: When updating outdated exercise with test changes, cannot re-run tests without making a change
Might be intended, but is confusing ;)

### PR DESCRIPTION
**Pull request by iHiD**
Fixes https://github.com/exercism/exercism/issues/6236
Fixes https://github.com/exercism/exercism/issues/6229

This does two things:
1. It fixes a bug where the wrong git_sha was being passed into the test runner.
2. This hardens the logic around updating an exercise. We now also update the most recent iteration's submission (ie the last meaningful submission the person did) to reflect the new git_sha, and we rerun the tests on that code. We **don't** as of yet rerun the analyzer/representer. Currently we (mentally) expect submission.git_sha to be immutable and so this breaks the (mental) model of how representers reference submissions, which will take some deeper thinking.

### CODE REVIEW

File: app/commands/tooling_job/create.rb [hunk 1]
```diff
@@ -22,7 +22,7 @@ def call
           submission_efs_root: submission.uuid,
           submission_filepaths: submission.valid_filepaths,
           exercise_git_repo: solution.track.slug,
-          exercise_git_sha: solution.git_sha,
+          exercise_git_sha: git_sha,
```
Comment (iHiD) [inline app/commands/tooling_job/create.rb:25]: This is the first bug mentioned in the description.

File: app/commands/solution/update_to_latest_exercise_version.rb [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+    initialize_with :solution
+
+    def call
+      solution.sync_git!
+      update_latest_iteration!
+    end
+
+    # This updates the submission of the latest iteration
+    # by setting its git_sha and then rerunning the tests
+    # in solution mode, which leads the status of the solution
```
Comment (ErikSchierboom) [inline app/commands/solution/update_to_latest_exercise_version.rb]:
```suggestion
    # in submission mode, which leads the status of the solution
```

File: test/commands/solution/update_to_latest_exercise_version_test.rb [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+
+    Solution::UpdateToLatestExerciseVersion.(solution)
+    [old_submission, new_submission, deleted_submission].each(&:reload)
+
+    assert_equal "foo", old_submission.git_sha
+    assert_equal "bar", old_submission.git_slug
+    assert_equal solution.exercise.git_sha, new_submission.git_sha
+    assert_equal solution.exercise.slug, new_submission.git_slug
+    assert_equal "foo", deleted_submission.git_sha
+    assert_equal "bar", deleted_submission.git_slug
```
Comment (ErikSchierboom) [inline test/commands/solution/update_to_latest_exercise_version_test.rb:40]: Nice test

**Review by ErikSchierboom — APPROVED** [review]
