### PR TITLE
Fix incorrect key serialization

### LINKED ISSUE #41: [Page iterations] : Syntax highlighting seems broken on some exercises' iterations
syntax-highlighting-pbm

Let me know if you need more information

### PR DESCRIPTION
**Pull request by iHiD**
Fixes https://github.com/exercism/v3-beta/issues/41

@ErikSchierboom @kntsoriano This was a mismatch in the key from Rails and the key in JS. Any thoughts on how we could have caught this with tests?

### CODE REVIEW

File: app/javascript/packs/application.tsx [hunk 1]
```diff
@@ -437,15 +437,18 @@ initReact({
...
-    <Student.IterationPage
-      solutionId={data.solution_id}
-      request={camelizeKeysAs<IterationPageRequest>(data.request)}
-      exercise={camelizeKeysAs<IterationPageExercise>(data.exercise)}
-      track={camelizeKeysAs<IterationPageTrack>(data.track)}
-      links={camelizeKeysAs<IterationPageLinks>(data.links)}
-    />
-  ),
+  'student-iteration-page': (data: any) => {
+    console.log(data.track)
```
Comment (joshgoebel) [inline app/javascript/packs/application.tsx]: Did you mean to keep this?

Comment (iHiD) [reply app/javascript/packs/application.tsx]: Nope. Thanks.

Comment (iHiD) [reply app/javascript/packs/application.tsx]:
```suggestion
```

File: app/javascript/components/mentoring/session/FileViewer.tsx [hunk 2]
```diff
@@ -16,7 +16,7 @@ export const FileViewer = ({
   return (
     <pre ref={parentRef}>
       <code
-        className={language}
+        className={`language-${language}`}
```
Comment (joshgoebel) [inline app/javascript/components/mentoring/session/FileViewer.tsx:19]: Yes, much nicer. :)
