### PR TITLE
Fix wrong file being downloaded

### LINKED ISSUE #5891: Different solutions on website and through client
[downloaded_version.zip](https://github.com/exercism/exercism/files/7165837/downloaded_version.zip)
I tried to mentor the first iteration of this solution on the C track:
https://exercism.org/mentoring/discussions/3f523caed8664e05ab997007268c4875

The first iteration looked like this on the website:  
`resistor_color.c`:
```c
#include "resistor_color.h"

resistor_band_t bandArray[10] = {BLACK, BROWN, RED, ORANGE, VIOLET, GREEN, BLUE, VIOLET, GREY, WHITE};
int color_code(resistor_band_t band) {
    return band;
}

resistor_band_t* colors(void) {
    return bandArray;
}
```
`resistor_color.h`:
```c
#ifndef RESISTOR_COLOR_H
#define RESISTOR_COLOR_H

typedef enum {
    BLACK = 0,
    BROWN = 1,
    RED = 2,
    ORANGE = 3,
    YELLOW = 4,
    GREEN = 5,
    BLUE = 6,
    VIOLET = 7,
    GREY = 8,
    WHITE = 9
} resistor_band_t;

int color_code(resistor_band_t band);

resistor_band_t* colors(void);

#endif

```

But when I downloaded the solution it looked like this:
`resistor_color.c`:
```c
#include "resistor_color.h"

resistor_band_t bandArray[10] = {BLACK, BROWN, RED, ORANGE, VIOLET, GREEN, BLUE, VIOLET, GREY, WHITE};

int color_code(resistor_band_t band) {
    return band;
}

resistor_band_t[] colors(void) {
    return bandArray;
}
```
`resistor_color.h`:
```c
#ifndef RESISTOR_COLOR_H
#define RESISTOR_COLOR_H

typedef enum {
    BLACK = 0,
    BROWN = 1,
    RED = 2,
    ORANGE = 3,
    YELLOW = 4,
    GREEN = 5,
    BLUE = 6,
    VIOLET = 7,
    GREY = 8,
    WHITE = 9
} resistor_band_t;

int color_code(resistor_band_t band);

resistor_band_t* colors(void);

#endif
```

There's a small difference in the `.c` file: On the website the return type is `resistor_band_t*`, in the downloaded version it's `resistor_band_t[] `.

I deleted that file and downloaded the solution again (`exercism download --uuid=799b4d189ebf495eb817754cbd62a4b6`) but the difference (`resistor_band_t[]`) was still there.

Since then the student has submitted a new (correct) iteration, so for the the issue is solved.

Now the question is: Why did that happen and how do we prevent that in the future?

### PR DESCRIPTION
**Pull request by iHiD**
Fixes https://github.com/exercism/exercism/issues/5891

The CLI was using latest submission, not the submission of the latest iteration.

### CODE REVIEW

**Review by chriseyre2000 — APPROVED** [review]
LGTM

File: test/controllers/api/v1/files_controller_test.rb [hunk 1]
```diff
@@ -44,16 +44,39 @@ class API::V1::FilesControllerTest < API::BaseTestCase
...
     content = "foobar!!"
     file = create :submission_file, submission: submission, content: content
+    create :iteration, solution: solution, submission: submission
 
     get "/api/v1/solutions/#{solution.uuid}/files/#{file.filename}", headers: @headers, as: :json
     assert_response 200
     assert_equal response.body, content
   end
 
+  test "show should latest iteration, not latest submission" do
```
Comment (ErikSchierboom) [inline test/controllers/api/v1/files_controller_test.rb]:
```suggestion
  test "show should return latest iteration, not latest submission" do
```

**Review by ErikSchierboom — APPROVED** [review]
