### PR TITLE
Fix nil-reference in files controller if all iterations are deleted

### LINKED ISSUE #2577: NoMethodError in api/v1/files#show
## Error in v3

**NoMethodError** in **api/v1/files#show**
undefined method `submission' for nil:NilClass

        solution.latest_iteration.submission
                                 ^^^^^^^^^^^

[View on Bugsnag](https://app.bugsnag.com/exercism/v3/errors/624c7f9c8731100008cd3793?event_id=624c7f9c00934bb703e60000&i=gh&m=ci)

## Stacktrace

    app/controllers/api/v1/files_controller.rb:14 - show
    app/controllers/application_controller.rb:12 - process_action

[View full stacktrace](https://app.bugsnag.com/exercism/v3/errors/624c7f9c8731100008cd3793?event_id=624c7f9c00934bb703e60000&i=gh&m=ci)

*Created automatically via Bugsnag*

### PR DESCRIPTION
**Pull request by ErikSchierboom**
Closes https://github.com/exercism/website/issues/2577

### CODE REVIEW

File: app/controllers/api/v1/files_controller.rb [hunk 1]
```diff
@@ -11,7 +11,7 @@ def show
 
       submission = solution.user == current_user ?
         solution.submissions.last :
-        solution.latest_iteration.submission
+        solution.latest_iteration&.submission
 
       content = submission.files.find_by(filename: params[:filepath])&.content if submission
```
Comment (iHiD) [inline app/controllers/api/v1/files_controller.rb:16]: Will this not blow up here because submission will be `nil`?

Comment (ErikSchierboom) [reply app/controllers/api/v1/files_controller.rb:16]: It won't, due to the `if submission` at the end.

**Review by iHiD — APPROVED** [review]
