### PR TITLE
Fix indentation in file viewer

### LINKED ISSUE #25: [Page: Editor] Inconsistent tab size.
I found this accidentally and am not even sure if one consider it a bug.

While solving a rust exercise and playing around with the setting "Tab enabled" I ended up submitting a file with different indentation styles (mixed spaces and tab) in the editor the file looks like this (Line 20 has tab indentation)

image

And in the "Your iterations" tab it looked like this (Line 20):

image

IMHO both options are fine but they should be consistent.

### PR DESCRIPTION
**Pull request by ErikSchierboom**
Closes https://github.com/exercism/v3-beta/issues/25

### CODE REVIEW

File: app/javascript/utils/highlight.ts [hunk 1]
```diff
@@ -49,7 +49,7 @@ function getLinesCount(text: string) {
 
 function wrapLineNumbers(code: string, start = 1) {
   const element = document.createElement('div')
-  element.innerHTML = code.trim()
+  element.innerHTML = code.replace(/(^[\r\n]+|[\r\n]+$)/g, '')
```
Comment (ErikSchierboom) [inline app/javascript/utils/highlight.ts]: This was causing the leading spaces/tabs to be removed. I've changed this to just removing newlines from the start and end.

File: app/javascript/components/mentoring/session/FileViewer.tsx [hunk 2]
```diff
@@ -17,8 +19,10 @@ export const FileViewer = ({
         className={language}
         data-highlight-line-numbers={true}
         data-highlight-line-number-start={1}
-        dangerouslySetInnerHTML={{ __html: file.content }}
-      />
+        style={{ tabSize: indentSize }}
```
Comment (ErikSchierboom) [inline app/javascript/components/mentoring/session/FileViewer.tsx:22]: As far as I could tell, this property is supported in all major browsers.

File: app/javascript/utils/highlight.ts (hunk 1 above)
Comment (iHiD) [inline app/javascript/utils/highlight.ts]: Could you add a comment to this line explaining what this does pls?

**Review by iHiD — APPROVED** [review]
