### PR TITLE
Revert to simpler localstorage hook

### LINKED ISSUE #289: Empty files cause infinite loop
@kntsoriano We have an issue where if the initial stub is empty, or you create an empty submission then refresh, stuff goes wrong.

See this video:
https://files.internetwolke.ovh/2020/11/ydncVtcAPD.mp4

I think there’s an issue with the local storage stuff. Maybe because `""` in JS is `false`, not `true` and some something is happening that you’re not expecting?

The Julia track has lots of empty stubs to experiment with (until @SaschaMann implements them :)). I've updated Julia/Lasagna as part of diagnosing this though.

### PR DESCRIPTION
**Pull request by kntsoriano**
Closes https://github.com/exercism/v3-website/issues/289.

When using the`useMemory` hook, it somehow changes `''` to `null`, which causes the revert code to not run properly. I'm unsure what causes this, but I decided to use the `localStorage` for now in order for us to not have this problem.

### CODE REVIEW

File: app/javascript/components/student/editor/FileEditor.tsx [hunk 1]
```diff
@@ -59,7 +59,7 @@ export const FileEditor = forwardRef<FileEditorHandle, FileEditorProps>(
     )
     const revertContent = useCallback(
       (e) => {
-        setContent(file.content)
+        editorRef.current?.setValue(file.content)
```
Comment (kntsoriano) [inline app/javascript/components/student/editor/FileEditor.tsx:62]: This was also a crucial line as Monaco editor doesn't behave like a controlled component.

**Review by ErikSchierboom — APPROVED** [review]
I'll leave this to @SleeplessByte who has much more knowledge about this :)

**Comment by iHiD** [comment]
This is red, @kntsoriano

**Comment by SleeplessByte** [comment]
I'll check out the hook and get back to you. Can merge this now, and I'll ping ya later 👍
