### PR TITLE
Hide favorite button

### LINKED ISSUE #176: Removing as favourite is broken.
https://www.loom.com/share/e1155a79c2f943c2982dbe7c789cfec3

### PR DESCRIPTION
**Pull request by kntsoriano**
Closes https://github.com/exercism/v3-beta/issues/176.

### CODE REVIEW

File: app/commands/mentor/student_relationship/toggle_favorited.rb [hunk 1]
```diff
@@ -6,14 +6,18 @@ class ToggleFavorited
...
+        return unless allowed?
 
         relationship = Mentor::StudentRelationship.create_or_find_by!(
           mentor: mentor,
           student: student
         )
         relationship.update_column(:favorited, favorited)
       end
+
+      def allowed?
```
Comment (kntsoriano) [inline app/commands/mentor/student_relationship/toggle_favorited.rb:18]: @iHiD I think the code will be cleaner if this lives within the `Mentor::StudentRelationship` model. I didn't do that right now though and opted for this change as I'll leave that for you to decide.

Comment (iHiD) [reply app/commands/mentor/student_relationship/toggle_favorited.rb:18]: OK, thanks. I'm ok with it here for now, but I agree that if we use it in multiple places it would be worth adding elsewhere :)
