### PR TITLE
Fix image assets URL

### LINKED ISSUE #6255: Broken image in concept exercise test results panel
Expanding and contracting the task results works, but the "contract" icon is broken:

image

### PR DESCRIPTION
**Pull request by ErikSchierboom**
Depends on https://github.com/exercism/config/pull/45 being merged for things to work locally

Closes https://github.com/exercism/exercism/issues/6255

### CODE REVIEW

File: app/javascript/esbuild.js [hunk 1]
```diff
@@ -28,7 +33,7 @@ function build() {
       define: {
         // TODO: move bugsnag API key into config
         'process.env.BUGSNAG_API_KEY': '"938ae3d231c5455e5c6597de1b1467af"',
-        'process.env.WEBSITE_ASSETS_HOST': `"${env['website_assets_host']}"`,
+        'process.env.WEBSITE_ASSETS_HOST': `"${assetsHost}"`,
```
Comment (iHiD) [inline app/javascript/esbuild.js]:
```suggestion
        'process.env.WEBSITE_ASSETS_HOST': `"${env['website_assets_host'] || ''}"`,
```

Maybe just?

**Review by kntsoriano — APPROVED** [review]
