### PR TITLE
Fix issue with non-iteration submissions and improve test performance

### LINKED ISSUE #6511: Export endpoint for testing the representer should return first iterations
I looked at 3 exercises so far. From the 500 solutions I got from the export endpoint, less then 200 compile and pass the tests. That makes the statistics rather "small".

Looking at those numbers, it feels to me the endpoint currently returns first submissions instead of first iterations (the successful ones coming from the CLI). I think it should return first iterations because this is what the representer will run on. Than, failing solutions can happen but should be rare.

(@ErikSchierboom here the issue as discussed)

### PR DESCRIPTION
**Pull request by iHiD**
- Fixes https://github.com/exercism/exercism/issues/6511
- Stops us from creating 500 solutions for the test (which took **ages**)

### CODE REVIEW

File: app/commands/exercise/export_solutions_to_zip_file.rb [hunk 1]
```diff
@@ -3,12 +3,15 @@
...
+  def self.num_submissions = 500
+
   initialize_with :exercise
 
   def call
     file_stream = Zip::OutputStream.write_buffer do |zip|
       solutions.each.with_index do |solution, idx|
-        submission = solution.submissions.first
+        submission = solution.iterations.first.submission
+        next unless submission
```
Comment (ErikSchierboom) [inline app/commands/exercise/export_solutions_to_zip_file.rb:14]: When would this condition be true? Just asking as this would cause the output to potentially not have 500 records. Which is fine, but might be odd.

**Review by ErikSchierboom — APPROVED** [review]

File: app/commands/exercise/export_solutions_to_zip_file.rb (hunk 1 above)
Comment (iHiD) [reply app/commands/exercise/export_solutions_to_zip_file.rb:14]: I was thinking if the first iteration is deleted. But we should probably change it to be `solution.iterations.first&.submission` for that case.

Comment (ErikSchierboom) [reply app/commands/exercise/export_solutions_to_zip_file.rb:14]: It probably doesn't really matter much

Comment (iHiD) [reply app/commands/exercise/export_solutions_to_zip_file.rb:14]: I think this will definitely fail without the guard for deleted iterations as that happens all the time. I'll update.
