### PR TITLE
Fix cursor issue on Windows

### LINKED ISSUE #742: Cursor in editor does not correspond to click location
I have a weird issue where the cursor does not correspond to the location that I click on with my mouse:

https://www.loom.com/share/f0d3b0c20b594885bd1219a5c5e4a109

CC @iHiD

### PR DESCRIPTION
**Pull request by ErikSchierboom**
Closes https://github.com/exercism/website/issues/742

### CODE REVIEW

File: app/javascript/components/editor/FileEditor.tsx [hunk 1]
```diff
@@ -100,6 +100,10 @@ export function FileEditor({
   ) => {
     editorRef.current = editor
 
+    // This fixes a Windows-only issue with the custom code font resulting in the cursor rendering being off
+    // See https://github.com/exercism/website/issues/742#issuecomment-816806513
+    monacoEditor.editor.remeasureFonts()
```
Comment (ErikSchierboom) [inline app/javascript/components/editor/FileEditor.tsx:105]: I've put this almost at the very top of the `handleEditorDidMount` function to indicate its importance to the user experience and to get it working as soon as possible. @kntsoriano is the right place to put this code?

Comment (kntsoriano) [reply app/javascript/components/editor/FileEditor.tsx:105]: Sounds good!

**Review by kntsoriano — APPROVED** [review]
