### PR TITLE
Make hints dialog accessible

### LINKED ISSUE #6470: Dialogue model not accessible with NVDA
Hi, 
I am using NVDA. I was trying to reveal the hints for one Python exercise by clicking on "Stuck? Reveal Hints
Opens in a modal"
But once the model appear, screen reader does not read anything. 
I have tried the same with JAWS 2019. It also does not work.

### PR DESCRIPTION
**Pull request by dem4ron**
Making TaskHintModal more accessible

Closes https://github.com/exercism/exercism/issues/6470

This is not yet implemented: https://github.com/exercism/exercism/issues/6475

### CODE REVIEW

**Comment by iHiD** [comment]
Git Message:

> accesible task hints dialog

to

> Make hints dialog accessible

(You can change this in the title of the PR and it'll update when it's merged)

**Comment by SleeplessByte** [comment]
What would be good in this case is trying out NVDA (or voiceover if you're on Mac) yo see if this actually solves the issue.

Using a screenreader at first is jarring but you'll get used to it fast.

**Comment by ErikSchierboom** [comment]
@SleeplessByte Do you have a sample page with a dialogue that has good accessibility? That way I can hear what it _supposed_ to sound like.

**Review by ErikSchierboom — APPROVED** [review]
It looks (and sounds) good to me.

@SleeplessByte any comments?

File: app/javascript/components/modals/TaskHintsModal.tsx [hunk 1]
```diff
@@ -14,20 +14,30 @@ export const TaskHintsModal = ({
...
-            className="c-textual-content --large"
-            key={idx}
-            dangerouslySetInnerHTML={{ __html: hint }}
-          ></div>
-        ))}
+    <Modal
+      open={open}
+      onClose={onClose}
+      aria={{
+        describedby: 'task-hints-description',
```
Comment (SleeplessByte) [inline app/javascript/components/modals/TaskHintsModal.tsx]: I would also add labelledby and link the title!

File: app/javascript/components/modals/TaskHintsModal.tsx [hunk 2]
```diff
@@ -14,20 +14,30 @@ export const TaskHintsModal = ({
...
+      }}
+      className="m-editor-hints"
+      {...props}
+    >
+      <div id="task-hints-description" role="document">
+        <header>
+          <GraphicalIcon icon="hints" category="graphics" />
+          <h2>Hints and Tips</h2>
```
Comment (SleeplessByte) [inline app/javascript/components/modals/TaskHintsModal.tsx]: This would be the dialog title

File: app/javascript/components/modals/TaskHintsModal.tsx [hunk 3]
```diff
@@ -14,20 +14,30 @@ export const TaskHintsModal = ({
...
-      <div className="single-task-hints">
-        <h3>{task.title}</h3>
-        {task.hints.map((hint, idx) => (
-          <div
-            className="c-textual-content --large"
-            key={idx}
-            dangerouslySetInnerHTML={{ __html: hint }}
-          ></div>
-        ))}
+    <Modal
```
Comment (SleeplessByte) [inline app/javascript/components/modals/TaskHintsModal.tsx:17]: Assuming this sets the correct role and aria properties...

Comment (SleeplessByte) [reply app/javascript/components/modals/TaskHintsModal.tsx:17]: If this does not add a hidden close button you may want to add one yourself but that can be a separate PR.

**Review by SleeplessByte — APPROVED** [review]
Looking good. Minor tips

File: app/javascript/components/modals/TaskHintsModal.tsx [hunk 4]
```diff
@@ -14,20 +14,30 @@ export const TaskHintsModal = ({
...
+      open={open}
+      onClose={onClose}
+      aria={{
+        describedby: 'task-hints-description',
+      }}
+      className="m-editor-hints"
+      {...props}
+    >
+      <div id="task-hints-description" role="document">
```
Comment (iHiD) [inline app/javascript/components/modals/TaskHintsModal.tsx]:
```suggestion
      <div id="a11y-task-hints-description" role="document">
```

Let's explicitly prefix these ids with `a11y` so that we understand that's what they're for and don't at some point in the future accidentally remove them, or refactor them out

File: app/javascript/components/modals/TaskHintsModal.tsx (hunk 2 above)
Comment (dem4ron) [reply app/javascript/components/modals/TaskHintsModal.tsx]: do you mean the Hints and Tips?
