### PR TITLE
Fix tutorial modal

### LINKED ISSUE #5856: "Return to  Hello World" does nothing
On the "Hello world" completion modal - "Return to  Hello World" does nothing. It should close the modal.

Screenshot 2021-09-09 at 22 05 36

### PR DESCRIPTION
**Pull request by kntsoriano**
Close https://github.com/exercism/exercism/issues/5856.

Instead of closing the modal as described in the issue, I decided to redirect the user back to the exercise page as this would contain the "completed" state for the exercise.

### CODE REVIEW

File: app/javascript/components/modals/complete-exercise-modal/TutorialCompletedModal.tsx [hunk 1]
```diff
@@ -40,17 +43,25 @@ export const TutorialCompletedModal = ({
...
         ) : (
-          <a href={track.links.exercises} className="btn-primary btn-m">
+          <a
+            href={completion.track.links.exercises}
+            className="btn-primary btn-m"
+          >
             Show me more exercises
           </a>
         )}
-        <button className="btn">Return to “Hello, World!”</button>
```
Comment (kntsoriano) [inline app/javascript/components/modals/complete-exercise-modal/TutorialCompletedModal.tsx:53]: @iHiD I decided to remove the hardcoded exercise names in this modal. I remember that there was a TODO for this in another component. We might want to apply the same here.

Comment (iHiD) [reply app/javascript/components/modals/complete-exercise-modal/TutorialCompletedModal.tsx:53]: OK, cool. You need to put `{completion.exercise.title}` back in quotes in the button to match what this originally was.

File: test/system/flows/complete_tutorial_test.rb [hunk 2]
```diff
@@ -22,7 +22,10 @@ class CompleteTutorialTest < ApplicationSystemTestCase
         click_on "Mark as complete"
         find("label", text: "Yes, I'd like to share my solution with the community.").click
         click_on "Confirm"
-        assert_text "You’ve completed “Hello, World!”"
+        assert_text "You’ve completed Hello World"
```
Comment (iHiD) [inline test/system/flows/complete_tutorial_test.rb]: This should be changed back.

**Comment by iHiD** [comment]
Cool, that makes sense. Added a couple of comments,
