### PR TITLE
Handle bad unicode rather than dealing with binary files

### LINKED ISSUE #1538: JSON::GeneratorError in api/solutions/submission_files#index
## Error in v3

**JSON::GeneratorError** in **api/solutions/submission_files#index**
Invalid Unicode [1b 00 00 00 00] at 41

[View on Bugsnag](https://app.bugsnag.com/exercism/v3/errors/612affa7656eac0008c767bb?event_id=612affa7007fa48d3c740000&i=gh&m=ci)

## Stacktrace

    app/controllers/api/solutions/submission_files_controller.rb:20 - index
    app/controllers/application_controller.rb:12 - process_action

[View full stacktrace](https://app.bugsnag.com/exercism/v3/errors/612affa7656eac0008c767bb?event_id=612affa7007fa48d3c740000&i=gh&m=ci)

*Created automatically via Bugsnag*

### LINKED ISSUE #1681: ActionView::Template::Error in tracks/exercises#edit
## Error in v3

**ActionView::Template::Error** in **tracks/exercises#edit**
Invalid Unicode [a0 b0 00 00 00] at 40

[View on Bugsnag](https://app.bugsnag.com/exercism/v3/errors/612f97e1d761d0000815786f?event_id=612f97e1007f8e07d7970000&i=gh&m=ci)

## Stacktrace

    app/helpers/react_components/react_component.rb:16 - to_s
    app/helpers/react_components/editor.rb:6 - to_s
    app/views/tracks/exercises/edit.html.haml:2 - _app_views_tracks_exercises_edit_html_haml___4162649472876387220_47266794576900
    app/controllers/application_controller.rb:12 - process_action

[View full stacktrace](https://app.bugsnag.com/exercism/v3/errors/612f97e1d761d0000815786f?event_id=612f97e1007f8e07d7970000&i=gh&m=ci)

*Created automatically via Bugsnag*

### PR DESCRIPTION
**Pull request by iHiD**
Closes https://github.com/exercism/website/issues/1681
Closes https://github.com/exercism/website/issues/1538

There's a more long-term solution of having a status field on each submission file so we can render things more neatly in the UI, but this at least fixes the issue for now.

### CODE REVIEW

File: test/models/submission/file_test.rb [hunk 1]
```diff
@@ -35,7 +35,10 @@ class SubmissionFileTest < ActiveSupport::TestCase
     # Get a new instance from the db so that we retrieve
     # from s3, not from the local cached version
     reloaded_file = Submission::File.find(file.id)
-    assert_equal "\xC2", reloaded_file.content
     assert_equal "\xC2", File.read(reloaded_file.efs_path)
+
+    # File should be turned into empty string
+    # it can't be turned into JSON.
```
Comment (ErikSchierboom) [inline test/models/submission/file_test.rb]:
```suggestion
    # if it can't be turned into JSON.
```

**Review by ErikSchierboom — APPROVED** [review]
