### PR TITLE
Fix video previews when requesting mentorship

### LINKED ISSUE #5794: Um, "Best practices writing feedback trrrrrruuuuunnnncaaatteeee" ?
image

### LINKED ISSUE #5799: Links to mentoring tips don't work
Clicking on these mentoring tip links doesn't do anything. All request in network tab return 200 and there are no errors in the console

https://user-images.githubusercontent.com/3275302/131737910-4a26c170-2f65-4f78-94f7-b00583170616.mp4

### PR DESCRIPTION
**Pull request by kntsoriano**
Closes https://github.com/exercism/exercism/issues/5794.
Closes https://github.com/exercism/exercism/issues/5799.

Screen Shot 2021-09-06 at 8 55 06 AM

Aside: I noticed that the link in the description and the link in the video point to the same thing. It doesn't really matter right now.

### CODE REVIEW

File: app/helpers/react_components/student/mentoring_session.rb [hunk 1]
```diff
@@ -68,22 +68,13 @@ def num_discussions_with_mentor
...
-            title: "Best practices writing feedback trrrrrruuuuunnnncaaatteeee",
-            date: Date.new(2020, 1, 24).iso8601
-          },
-          {
-            url: "#",
-            title: "Beginners’ Guide to Mentoring",
-            date: Date.new(2020, 1, 24).iso8601
+            url: Exercism::Routes.doc_path(:using, "feedback/guide-to-being-mentored"),
+            # TODO: Change this
+            thumb: "https://i.vimeocdn.com/video/1230063662?mw=800&mh=450",
```
Comment (kntsoriano) [inline app/helpers/react_components/student/mentoring_session.rb]: I added this in order for us to be able to configure the thumbnail. I just ripped the thumbnail from the video so we should change this.

File: app/javascript/components/student/mentoring-session/mentoring-request/MentoringRequestInfo.tsx [hunk 2]
```diff
@@ -112,10 +112,17 @@ export const MentoringRequestInfo = ({
   )
 }
 
-const Video = ({ title, date, url }: VideoProps) => {
+const Video = ({ title, date, thumb, url }: VideoProps) => {
   return (
-    <a href={url} className="video">
-      <div className="img" />
+    <a href={url} target="_blank" rel="noreferrer" className="video">
+      <div
```
Comment (kntsoriano) [inline app/javascript/components/student/mentoring-session/mentoring-request/MentoringRequestInfo.tsx:118]: Can you check if you are happy with this? Or should we do it a different way?
