### PR TITLE
Open issue for prerequisite cycles

### LINKED ISSUE #1210: TrackHasCyclicPrerequisiteError in tracks/concepts#index
## Error in v3

**TrackHasCyclicPrerequisiteError** in **tracks/concepts#index**
TrackHasCyclicPrerequisiteError

[View on Bugsnag](https://app.bugsnag.com/exercism/v3/errors/60e36940eb20fe00076401e8?event_id=60e36940007f9561c4320000&i=gh&m=ci)

## Stacktrace

    app/commands/track/determine_concept_map_layout.rb:63 - node_levels
    app/commands/track/determine_concept_map_layout.rb:43 - concept_levels
    app/commands/track/determine_concept_map_layout.rb:19 - call
    app/controllers/tracks/concepts_controller.rb:9 - index

[View full stacktrace](https://app.bugsnag.com/exercism/v3/errors/60e36940eb20fe00076401e8?event_id=60e36940007f9561c4320000&i=gh&m=ci)

*Created automatically via Bugsnag*

### PR DESCRIPTION
**Pull request by ErikSchierboom**
This PR adds functionality to automatically open an issue when a dependency cycle is found in a track's concept map.
For an example, see https://github.com/ErikSchierboom/go/issues/10. 

Let me know what you think of the issue body. I did not include the stacktrack because it wasn't really helpful. Once you're happy with the text, I'll create an issue on the Go repo (which was the repo with the cycles).

I've also refactored a bit to allow sharing the open/reopen issue on GitHub functionality between commands.

Closes https://github.com/exercism/website/issues/1210

### CODE REVIEW

File: app/commands/track/determine_concept_map_layout.rb [hunk 1]
```diff
@@ -19,6 +19,8 @@ def call
         levels: concept_levels,
         connections: concept_connections
       }
+    rescue TrackHasCyclicPrerequisiteError
+      Github::Issue::OpenForDependencyCycle.(track)
```
Comment (iHiD) [inline app/commands/track/determine_concept_map_layout.rb]: This should needs wrapping as a job, as this is happening in-progress for the user.

I think we should also then re-raise the exception (you can use `raise` with no args), and catch and handle it in the UI.

File: app/commands/github/issue/open.rb [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+      include Mandate
+
+      initialize_with :repo, :title, :body
+
+      def call
+        if missing?
+          create_issue
+        elsif closed?
+          reopen_issue
+        end
```
Comment (ErikSchierboom) [inline app/commands/github/issue/open.rb:13]: There is a risk of duplicate issues being created if this is called in parallel. Do we want to guard against that?

File: app/jobs/open_issue_for_dependency_cycle_job.rb [hunk 3]
```diff
@@ -0,0 +1,7 @@
+class OpenIssueForDependencyCycleJob < ApplicationJob
+  queue_as :default
```
Comment (ErikSchierboom) [inline app/jobs/open_issue_for_dependency_cycle_job.rb:2]: Is this the right queue?

Comment (iHiD) [reply app/jobs/open_issue_for_dependency_cycle_job.rb:2]: Yeah, it's fine.
