### PR TITLE
Return 404 for missing docs

### LINKED ISSUE #6341: Docs with a slug that doesn't exist result in 500 instead of 404
Correct (anything but docs): https://exercism.org/tracks/surely-this-does-not-exist

Incorrect: https://exercism.org/docs/xvcbcvb

@ErikSchierboom 

Related: #5680

### PR DESCRIPTION
**Pull request by ErikSchierboom**
This PR ensures that a 404 is rendered when a document is not found, instead of a 500 (which would 
also result in a bugsnag entry I believe).
Whilst implementing this, I found that unit tests were a bit lacking, so I added some.

- Rename tests for docs controller
- Add tests for docs section
- Add tests for docs tracks section
- Add tests for docs track index section
- Add tests for docs track doc section
- Add 404 tests to docs controller tests
- Simplify code a bit

Closes https://github.com/exercism/exercism/issues/6341

### CODE REVIEW

File: app/controllers/docs_controller.rb [hunk 1]
```diff
@@ -7,23 +7,29 @@ class DocsController < ApplicationController
...
-    @doc = Document.find_by(section: @section, slug: "APEX")
+    @doc = Document.find_by!(section: @section, slug: "APEX")
     render action: :show
+  rescue ActiveRecord::RecordNotFound
+    render_404
   end
 
   def show
-    @doc = Document.where(section: @section).find(params[:slug])
+    @doc = @nav_docs.find(params[:slug])
```
Comment (ErikSchierboom) [inline app/controllers/docs_controller.rb:15]: `@nav_docs` has the same code as `Document.where(section: @section)` and is set in `use_section`, which is automatically called.

File: app/controllers/docs_controller.rb [hunk 2]
```diff
@@ -7,23 +7,29 @@ class DocsController < ApplicationController
...
+    render_404
   end
 
   def tracks; end
 
   def track_index; end
 
   def track_show
-    @doc = Document.where(track: @track).find(params[:slug])
+    @doc = @nav_docs.find(params[:slug])
```
Comment (ErikSchierboom) [inline app/controllers/docs_controller.rb:24]: Same as above, but with `use_track` instead of `use_section`.

File: app/controllers/docs_controller.rb [hunk 3]
```diff
@@ -7,23 +7,29 @@ class DocsController < ApplicationController
   def index; end
 
   def section
-    @doc = Document.find_by(section: @section, slug: "APEX")
+    @doc = Document.find_by!(section: @section, slug: "APEX")
```
Comment (ErikSchierboom) [inline app/controllers/docs_controller.rb:10]: I've changed to `find_by!` to raise an error when the document is not found.

File: app/controllers/docs_controller.rb [hunk 4]
```diff
@@ -7,23 +7,29 @@ class DocsController < ApplicationController
...
     render action: :show
+  rescue ActiveRecord::RecordNotFound
+    render_404
```
Comment (iHiD) [inline app/controllers/docs_controller.rb]: Out of interest, do you need this? I'd have guessed Rails would gracefully handle the `ActiveRecord::RecordNotFound` to show a 404.

File: app/controllers/docs_controller.rb [hunk 5]
```diff
@@ -7,23 +7,29 @@ class DocsController < ApplicationController
...
   end
 
   def show
-    @doc = Document.where(section: @section).find(params[:slug])
+    @doc = @nav_docs.find(params[:slug])
     render action: :show
+  rescue ActiveRecord::RecordNotFound
+    render_404
```
Comment (iHiD) [inline app/controllers/docs_controller.rb]: Same question.

File: app/controllers/docs_controller.rb (hunk 4 above)
Comment (ErikSchierboom) [reply app/controllers/docs_controller.rb]: You are correct. I've checked this by changing `config.consider_all_requests_local = true` to `config.consider_all_requests_local = false` in `config/environments/development.rb`.

The only "downside" is that the tests will change from

```ruby
get docs_section_path(:mentoring)
assert_rendered_404
```

to:

```ruby
assert_raises ActiveRecord::RecordNotFound do
  get docs_section_path(:mentoring)
end
```

I like the former a bit better.

Comment (iHiD) [reply app/controllers/docs_controller.rb]: So, I think it's definitely not idiomatic to be catching ActiveRecord::RecordNotFound and reraising as 404s, so we shouldn't do it.

I agree about the tests though. I'm surprised the first doesn't work tbh. I'd have thought it would have done reflected the production output more. But I think we probably just have to live with the uglier tests.

Comment (ErikSchierboom) [reply app/controllers/docs_controller.rb]: > I agree about the tests though. I'm surprised the first doesn't work tbh.

Well, that's because `environments/test.rb` has the same define:

```ruby
config.consider_all_requests_local = true
```

Do we want that?

Comment (iHiD) [reply app/controllers/docs_controller.rb]: Yeah, I imagine we should leave it as it is. But I just figured Rails would be smarter, despite that :)

File: config/environments/development.rb [hunk 6]
```diff
@@ -19,7 +19,7 @@
   config.eager_load = false
 
   # Show full error reports.
-  config.consider_all_requests_local = true
+  config.consider_all_requests_local = false
```
Comment (iHiD) [inline config/environments/development.rb]: Revert this.

Comment (ErikSchierboom) [inline config/environments/development.rb]:
```suggestion
  config.consider_all_requests_local = true
```

**Review by iHiD — APPROVED** [review]
