### PR TITLE
Remove student mentor relationships when account is deleted

### LINKED ISSUE #5926: Account deletion option does not work as intended.
Choosing to delete an account seems to reset the account instead. All track progress and public profile are removed but the account still remains.

### PR DESCRIPTION
**Pull request by iHiD**
Should resolve https://github.com/exercism/exercism/issues/5926

### CODE REVIEW

File: app/commands/user/reset_account.rb [hunk 1]
```diff
@@ -33,6 +33,7 @@ def reset_mentoring!
       user.mentor_discussions.update_all(mentor_id: User::GHOST_USER_ID)
       user.mentor_discussion_posts.update_all(user_id: User::GHOST_USER_ID)
       user.mentor_testimonials.update_all(mentor_id: User::GHOST_USER_ID)
+      user.mentor_testimonials.update_all(mentor_id: User::GHOST_USER_ID)
```
Comment (ErikSchierboom) [inline app/commands/user/reset_account.rb]: Isn't this the exact same line as the line above it?

Comment (iHiD) [reply app/commands/user/reset_account.rb]: Dammed fat vim fingers. Yes. Thanks.

**Review by ErikSchierboom — APPROVED** [review]
