### PR TITLE
Fix modal background

### LINKED ISSUE #337: Clicking on background should close modals.
Did you do this deliberately, or did I do it accidently.

### PR DESCRIPTION
**Pull request by kntsoriano**
Closes https://github.com/exercism/v3-beta/issues/337.

@iHiD Could you check if you are happy with this?

### CODE REVIEW

File: app/javascript/components/modals/Modal.tsx [hunk 1]
```diff
@@ -31,14 +31,17 @@ export const Modal = ({
     `theme-${theme}`,
     className,
     cover ? '--cover' : '',
+    '--modal-container',
   ]
 
+  console.log(onClose)
+
```
Comment (iHiD) [inline app/javascript/components/modals/Modal.tsx]:
```suggestion
```
